### PR TITLE
.gitignore additions

### PR DESCRIPTION
**Pull request by gmaldona**
* Removed DS_Store at the project root
* Added vscode personal configurations to gitignore

### CODE REVIEW

**Comment by AndrewTedesco** [comment]
iirc the .vscode folder is used by vex to store project information, and the contents are auto generated when creating a project. People also had issues with errors showing up when they downloaded the code from the github when it used to not have the .vscode folder, so I don't think it can be safely ignored.

DS_store can definitely be removed

**Comment by gmaldona** [comment]
> iirc the .vscode folder is used by vex to store project information, and the contents are auto generated when creating a project. People also had issues with errors showing up when they downloaded the code from the github when it used to not have the .vscode folder, so I don't think it can be safely ignored.
> 
> DS_store can definitely be removed



> iirc the .vscode folder is used by vex to store project information, and the contents are auto generated when creating a project. People also had issues with errors showing up when they downloaded the code from the github when it used to not have the .vscode folder, so I don't think it can be safely ignored.
> 
> DS_store can definitely be removed

ah okay, I just pulled in main with the updated changes to the c_cpp_properties.json and it seems to be generic enough for intelliSense to work. I was having intelliSense issues and added a few paths to fix it that didn't make sense to VC so ignored it but it looks like the recent changes fixes that 👍 updating the PR

**Comment by gmaldona** [comment]
leaving *code-workspace because its user specific

**Review by AndrewTedesco — APPROVED** [review]
looks good. merging

**Pull request merged**
